from enum import Enum, IntEnum

class AtomTypeEnumZinc(str, Enum):
    N = "N"
    P = "P"
    F = "F"
    C = "C"
    Br = "Br"
    S = "S"
    I = "I"
    Cl = "Cl"
    O = "O"

class BondTypeEnumZinc(Enum):
    SINGLE = 'SINGLE'
    DOUBLE = 'DOUBLE'
    TRIPLE = 'TRIPLE'
    AROMATIC = 'AROMATIC'

class AtomTypeEnumQM9(Enum):
    O = 'O'
    C = 'C'
    F = 'F'
    N = 'N'

class BondTypeEnumQM9(Enum):
    SINGLE = 'SINGLE'
    DOUBLE = 'DOUBLE'
    TRIPLE = 'TRIPLE'
    AROMATIC = 'AROMATIC'

# class AtomEnum(str, Enum):
#     # H = "H"
#     N = "N"
#     P = "P"
#     F = "F"
#     C = "C"
#     Br = "Br"
#     S = "S"
#     I = "I"
#     Cl = "Cl"
#     O = "O"

class AtomTypeEnum(Enum):
    H = 'H'
    He = 'He'
    Li = 'Li'
    Be = 'Be'
    B = 'B'
    C = 'C'
    N = 'N'
    O = 'O'
    F = 'F'
    Ne = 'Ne'
    Na = 'Na'
    Mg = 'Mg'
    Al = 'Al'
    Si = 'Si'
    P = 'P'
    S = 'S'
    Cl = 'Cl'
    Ar = 'Ar'
    K = 'K'
    Ca = 'Ca'
    Sc = 'Sc'
    Ti = 'Ti'
    V = 'V'
    Cr = 'Cr'
    Mn = 'Mn'
    Fe = 'Fe'
    Co = 'Co'
    Ni = 'Ni'
    Cu = 'Cu'
    Zn = 'Zn'
    Ga = 'Ga'
    Ge = 'Ge'
    As = 'As'
    Se = 'Se'
    Br = 'Br'
    Kr = 'Kr'
    Rb = 'Rb'
    Sr = 'Sr'
    Y = 'Y'
    Zr = 'Zr'
    Nb = 'Nb'
    Mo = 'Mo'
    Tc = 'Tc'
    Ru = 'Ru'
    Rh = 'Rh'
    Pd = 'Pd'
    Ag = 'Ag'
    Cd = 'Cd'
    In = 'In'
    Sn = 'Sn'
    Sb = 'Sb'
    Te = 'Te'
    I = 'I'
    Xe = 'Xe'
    Cs = 'Cs'
    Ba = 'Ba'
    La = 'La'
    Ce = 'Ce'
    Pr = 'Pr'
    Nd = 'Nd'
    Pm = 'Pm'
    Sm = 'Sm'
    Eu = 'Eu'
    Gd = 'Gd'
    Tb = 'Tb'
    Dy = 'Dy'
    Ho = 'Ho'
    Er = 'Er'
    Tm = 'Tm'
    Yb = 'Yb'
    Lu = 'Lu'
    Hf = 'Hf'
    Ta = 'Ta'
    W = 'W'
    Re = 'Re'
    Os = 'Os'
    Ir = 'Ir'
    Pt = 'Pt'
    Au = 'Au'
    Hg = 'Hg'
    Tl = 'Tl'
    Pb = 'Pb'
    Bi = 'Bi'
    Po = 'Po'
    At = 'At'
    Rn = 'Rn'
    Fr = 'Fr'
    Ra = 'Ra'
    Ac = 'Ac'
    Th = 'Th'
    Pa = 'Pa'
    U = 'U'
    Np = 'Np'
    Pu = 'Pu'
    Am = 'Am'
    Cm = 'Cm'
    Bk = 'Bk'
    Cf = 'Cf'
    Es = 'Es'
    Fm = 'Fm'
    Md = 'Md'
    No = 'No'
    Lr = 'Lr'
    Rf = 'Rf'
    Db = 'Db'
    Sg = 'Sg'
    Bh = 'Bh'
    Hs = 'Hs'
    Mt = 'Mt'
    Ds = 'Ds'
    Rg = 'Rg'
    Cn = 'Cn'
    Nh = 'Nh'
    Fl = 'Fl'
    Mc = 'Mc'
    Lv = 'Lv'
    Ts = 'Ts'
    Og = 'Og'

class BondTypeEnum(Enum):
    SINGLE = 'SINGLE'
    DOUBLE = 'DOUBLE'
    TRIPLE = 'TRIPLE'
    AROMATIC = 'AROMATIC'